# Generated by Django 5.2.5 on 2025-09-24 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_add_profile_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="cap",
            field=models.CharField(
                blank=True,
                help_text="CAP / codice postale (opzionale)",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="city",
            field=models.CharField(
                blank=True,
                help_text="Città dell'utente (opzionale)",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="skills",
            field=models.TextField(
                blank=True, help_text="Comma-separated skills", null=True
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="via",
            field=models.CharField(
                blank=True,
                help_text="Via / indirizzo (opzionale)",
                max_length=255,
                null=True,
            ),
        ),
    ]
