# Generated by Django 4.2.11 on 2025-07-05 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('lesson_purchased', 'Acquisto Lezione'), ('course_purchased', 'Acquisto Corso'), ('course_sold', 'Corso Venduto'), ('lesson_sold', 'Lezione Venduta'), ('exercise_graded', 'Esercizio Valutato'), ('review_assigned', 'Esercizio da valutare'), ('review_completed', 'Review Completata'), ('review_expired', 'Review scaduta'), ('review_replaced', 'Reviewer rimpiazzato'), ('course_completed', 'Corso Completato'), ('teacher_approved', 'Teacher approvato'), ('teacher_rejected', 'Teacher rifiutato'), ('course_approved', 'Corso approvato'), ('course_rejected', 'Corso rifiutato'), ('teocoins_earned', 'TeoCoins Guadagnati'), ('teocoins_spent', 'TeoCoins Spesi'), (
                'reward_earned', 'Premio Ottenuto'), ('bonus_received', 'Bonus Ricevuto'), ('teocoin_discount_pending', 'TeoCoin Discount - Teacher Decision Required'), ('teocoin_discount_accepted', 'TeoCoin Discount - Accepted by Teacher'), ('teocoin_discount_rejected', 'TeoCoin Discount - Rejected by Teacher'), ('teocoin_discount_expired', 'TeoCoin Discount - Expired (Auto-Rejected)'), ('new_course_published', 'Nuovo Corso Pubblicato'), ('new_lesson_added', 'Nuova Lezione Aggiunta'), ('course_updated', 'Corso Aggiornato'), ('achievement_unlocked', 'Achievement Sbloccato'), ('level_up', 'Livello Aumentato'), ('system_message', 'Messaggio di Sistema'), ('welcome_message', 'Messaggio di Benvenuto')], max_length=30),
        ),
    ]
