# Generated by Django 4.2.11 on 2025-08-09 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_alter_notification_notification_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="link",
            field=models.CharField(
                blank=True,
                help_text="URL di destinazione per azione diretta",
                max_length=255,
                null=True,
            ),
        ),
    ]
