version: "3.9"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app
      POSTGRES_USER: postgres
    ports: [ "5432:5432" ]
    volumes: [ "pgdata:/var/lib/postgresql/data" ]

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file: [ ./backend/.env ]
    # Entrypoint handles migrations; we still run collectstatic at start to be safe.
    command: >
      sh -c "python manage.py collectstatic --noinput || true && exec gunicorn schoolplatform.wsgi:application -b 0.0.0.0:8000 --access-logfile -"
    ports: [ "8000:8000" ]
    depends_on: [ db ]
    volumes:
      - ./backend:/app

  frontend:
    image: node:20
    working_dir: /fe
    volumes: [ "./lms-frontend:/fe" ]
    environment:
      - VITE_API_BASE_URL=http://localhost:8000
    command: sh -c "npm ci --also=dev && npm run dev -- --host"
    ports: [ "5173:5173" ]
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"

  # Optional services (enable later if needed)
  # redis:
  #   image: redis:7
  #   ports: [ "6379:6379" ]
  # minio:
  #   image: minio/minio:latest
  #   command: server /data --console-address ":9001"
  #   environment:
  #     MINIO_ROOT_USER: minioadmin
  #     MINIO_ROOT_PASSWORD: minioadmin
  #   ports: [ "9000:9000", "9001:9001" ]
  #   volumes: [ "minio:/data" ]
  # mailhog:
  #   image: mailhog/mailhog
  #   ports: [ "8025:8025" ]

volumes:
  pgdata:
