# Generated by Django 5.2.5 on 2025-09-01 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blockchain", "0005_alter_dbteocoinbalance_available_balance_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dbteocointransaction",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("earned", "Earned (Rewards/Teaching)"),
                    ("spent_discount", "Spent on Discount"),
                    ("staked", "Staked for Commission"),
                    ("unstaked", "Unstaked"),
                    ("withdrawn", "Withdrawn to MetaMask"),
                    ("deposit", "Deposited from MetaMask"),
                    ("bonus", "Platform Bonus"),
                    ("migration", "Migrated from Blockchain"),
                    ("discount_accept", "Discount Accept - Teacher accepted TEO"),
                ],
                max_length=20,
            ),
        ),
    ]
