# Generated by Django 4.2.11 on 2025-07-08 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeoCoinDiscountRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('student_address', models.CharField(
                    help_text="Student's wallet address", max_length=42)),
                ('teacher_address', models.CharField(
                    help_text="Teacher's wallet address", max_length=42)),
                ('course_id', models.PositiveIntegerField(
                    help_text='ID of the course being purchased')),
                ('course_price', models.PositiveIntegerField(
                    help_text='Original course price in cents (EUR)')),
                ('discount_percent', models.PositiveIntegerField(
                    help_text='Discount percentage in basis points (1000 = 10%)')),
                ('teo_cost', models.PositiveBigIntegerField(
                    help_text='TEO tokens student pays (in wei, 18 decimals)')),
                ('teacher_bonus', models.PositiveBigIntegerField(
                    help_text='Bonus TEO for teacher if accepted (in wei, 18 decimals)')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Pending'), (1, 'Approved'), (
                    2, 'Declined'), (3, 'Expired')], default=0, help_text='Current status of the discount request')),
                ('created_at', models.DateTimeField(
                    auto_now_add=True, help_text='When the request was created')),
                ('expires_at', models.DateTimeField(
                    help_text='When the request expires (auto-EUR)')),
                ('teacher_decision_at', models.DateTimeField(blank=True,
                 help_text='When teacher made their decision', null=True)),
                ('decline_reason', models.TextField(blank=True,
                 help_text='Optional reason if teacher declined')),
                ('blockchain_tx_hash', models.CharField(
                    blank=True, help_text='Transaction hash for blockchain operations', max_length=66)),
            ],
            options={
                'verbose_name': 'TeoCoin Discount Request',
                'verbose_name_plural': 'TeoCoin Discount Requests',
                'db_table': 'blockchain_teocoin_discount_request',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['student_address', 'status'], name='blockchain__student_ed6b9d_idx'), models.Index(fields=['teacher_address', 'status'], name='blockchain__teacher_7352e7_idx'), models.Index(fields=['course_id'], name='blockchain__course__cac54b_idx'), models.Index(fields=['expires_at'], name='blockchain__expires_9d1938_idx')],
            },
        ),
    ]
