# Generated by Django 4.2.11 on 2025-08-04 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "services",
            "0002_stakingactivity_platformgasexpense_platformallowance_and_more",
        ),
    ]

    operations = [
        migrations.DeleteModel(
            name="TeoEarning",
        ),
    ]
