# Generated by Django 4.2.11 on 2025-07-05 01:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0004_remove_course_price"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("rewards", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blockchaintransaction",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("mint", "Mint - Crea nuovi token"),
                    ("transfer", "Transfer - Trasferimento tra wallet"),
                    ("burn", "Burn - Distruzione token"),
                    ("course_purchase", "Course Purchase - Acquisto corso"),
                    ("course_earned", "Course Earned - Guadagno insegnante"),
                    ("reward", "Reward - Premio per attività"),
                    (
                        "exercise_reward",
                        "Exercise Reward - Premio per esercizio completato",
                    ),
                    ("review_reward", "Review Reward - Premio per review completata"),
                    ("discount_applied", "Discount Applied - Sconto TeoCoin applicato"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="TeoCoinEscrow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "teocoin_amount",
                    models.DecimalField(
                        decimal_places=8,
                        help_text="Amount of TeoCoin held in escrow",
                        max_digits=18,
                    ),
                ),
                (
                    "discount_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Percentage discount applied (e.g., 10.00 for 10%)",
                        max_digits=5,
                    ),
                ),
                (
                    "discount_euro_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Euro amount of discount",
                        max_digits=10,
                    ),
                ),
                (
                    "original_course_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Original course price in EUR",
                        max_digits=10,
                    ),
                ),
                (
                    "standard_euro_commission",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="EUR commission if teacher rejects TeoCoin",
                        max_digits=10,
                    ),
                ),
                (
                    "reduced_euro_commission",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="EUR commission if teacher accepts TeoCoin",
                        max_digits=10,
                    ),
                ),
                (
                    "escrow_tx_hash",
                    models.CharField(
                        blank=True,
                        help_text="Transaction hash for TeoCoin transfer to escrow",
                        max_length=66,
                        null=True,
                    ),
                ),
                (
                    "release_tx_hash",
                    models.CharField(
                        blank=True,
                        help_text="Transaction hash for TeoCoin release from escrow",
                        max_length=66,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Teacher Decision"),
                            ("accepted", "Teacher Accepted - TeoCoin Released"),
                            ("rejected", "Teacher Rejected - TeoCoin Returned"),
                            ("expired", "Expired - Auto Returned to Platform"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        help_text="Auto-reject escrow after this datetime"
                    ),
                ),
                (
                    "teacher_decision_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When teacher made their decision",
                        null=True,
                    ),
                ),
                (
                    "teacher_decision_notes",
                    models.TextField(
                        blank=True,
                        help_text="Optional notes from teacher about their decision",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teocoin_escrows",
                        to="courses.course",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teocoin_escrows_as_student",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teocoin_escrows_as_teacher",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "TeoCoin Escrow",
                "verbose_name_plural": "TeoCoin Escrows",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "expires_at"],
                        name="rewards_teo_status_d3b3ae_idx",
                    ),
                    models.Index(
                        fields=["teacher", "status"],
                        name="rewards_teo_teacher_d95a0d_idx",
                    ),
                    models.Index(
                        fields=["student", "created_at"],
                        name="rewards_teo_student_53d22a_idx",
                    ),
                ],
            },
        ),
    ]
