# Generated by Django 5.2.5 on 2025-08-26 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rewards", "0003_teacherpayoutsummary_teacherdiscountabsorption"),
    ]

    operations = [
        migrations.DeleteModel(
            name="TeoCoinEscrow",
        ),
    ]
