# Generated by Django 5.2.5 on 2025-08-26 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rewards", "0006_add_unique_orderid"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="paymentdiscountsnapshot",
            name="unique_order_id_snapshot",
        ),
        migrations.AlterField(
            model_name="paymentdiscountsnapshot",
            name="order_id",
            field=models.CharField(db_index=True, max_length=120, unique=True),
        ),
    ]
