# Generated by Django 5.2.5 on 2025-08-28 06:59

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rewards", "0008_paymentdiscountsnapshot_external_txn_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentdiscountsnapshot",
            name="closed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="paymentdiscountsnapshot",
            name="final_teacher_teo",
            field=models.DecimalField(
                blank=True,
                decimal_places=8,
                default=Decimal("0"),
                max_digits=18,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="paymentdiscountsnapshot",
            name="status",
            field=models.CharField(
                choices=[("pending", "Pending"), ("closed", "Closed")],
                db_index=True,
                default="pending",
                max_length=20,
            ),
        ),
    ]
