# Generated by Django 4.2.11 on 2025-06-22 03:35

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='price_eur',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Prezzo in Euro per pagamento fiat', max_digits=10),
        ),
        migrations.AddField(
            model_name='course',
            name='teocoin_discount_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('10.00'), help_text='Percentuale sconto pagando con TeoCoin', max_digits=5),
        ),
        migrations.AddField(
            model_name='course',
            name='teocoin_reward',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='TeoCoin ricompensa per completamento corso', max_digits=10),
        ),
        migrations.AddField(
            model_name='courseenrollment',
            name='amount_paid_eur',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount paid in EUR for fiat payments', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='courseenrollment',
            name='amount_paid_teocoin',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount paid in TeoCoin for crypto payments', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='courseenrollment',
            name='completed_at',
            field=models.DateTimeField(blank=True, help_text='Date when course was completed', null=True),
        ),
        migrations.AddField(
            model_name='courseenrollment',
            name='payment_method',
            field=models.CharField(choices=[('fiat', 'Euro Payment'), ('teocoin', 'TeoCoin Payment'), ('free', 'Free Course'), ('admin', 'Admin Granted')], default='free', max_length=10),
        ),
        migrations.AddField(
            model_name='courseenrollment',
            name='stripe_payment_intent_id',
            field=models.CharField(blank=True, help_text='Stripe payment intent ID for fiat payments', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='courseenrollment',
            name='teocoin_reward_given',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='TeoCoin reward given for course purchase', max_digits=10),
        ),
    ]
