# Generated by Django 5.2.5 on 2025-09-01 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0006_teacherchoicepreference_teacherdiscountdecision"),
    ]

    operations = [
        migrations.AddField(
            model_name="exercisereview",
            name="comment",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="exercisereview",
            name="creative",
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="exercisereview",
            name="following",
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="exercisereview",
            name="recommendations",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="exercisereview",
            name="technical",
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
