# Generated by Django 5.2.5 on 2025-09-08 09:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0007_exercisereview_comment_exercisereview_creative_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="approved_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp quando il corso è stato approvato da un admin",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Admin che ha approvato il corso",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_courses",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
