# Generated by Django 5.2.5 on 2025-09-08 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0009_peerreviewfeedbackitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="peerreviewfeedbackitem",
            name="review",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="feedback_items",
                to="courses.exercisereview",
            ),
        ),
    ]
