# Generated by Django 5.2.5 on 2025-09-12 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0013_remove_comment_and_recommendations"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teacherdiscountdecision",
            name="teacher_bonus",
            field=models.DecimalField(
                decimal_places=0,
                help_text="Teacher bonus in wei (18 decimals)",
                max_digits=30,
            ),
        ),
        migrations.AlterField(
            model_name="teacherdiscountdecision",
            name="teo_cost",
            field=models.DecimalField(
                decimal_places=0,
                help_text="TEO cost in wei (18 decimals)",
                max_digits=30,
            ),
        ),
    ]
