# Generated by Django 4.2.11 on 2025-06-22 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_add_fiat_payment_fields'),
    ]

    operations = [
    ]
