# Generated by Django 4.2.11 on 2025-06-30 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0003_add_fiat_payment_fields"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="price",
        ),
    ]
