# Generated by Django 4.2.11 on 2025-07-09 01:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0005_courseenrollment_discount_amount_eur_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherChoicePreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('preference', models.CharField(choices=[('always_accept', 'Always Accept TeoCoin'), ('always_decline', 'Always Decline TeoCoin'), (
                    'manual', 'Manual Decision Required'), ('threshold_based', 'Accept if TEO value > threshold')], default='manual', max_length=20)),
                ('minimum_teo_threshold', models.DecimalField(blank=True, decimal_places=2,
                 help_text='Minimum TEO amount to auto-accept', max_digits=10, null=True)),
                ('email_notifications', models.BooleanField(default=True)),
                ('immediate_notifications', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('teacher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,
                 related_name='choice_preference', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Preferenza Scelta Teacher',
                'verbose_name_plural': 'Preferenze Scelte Teacher',
            },
        ),
        migrations.CreateModel(
            name='TeacherDiscountDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('course_price', models.DecimalField(
                    decimal_places=2, max_digits=10)),
                ('discount_percentage', models.IntegerField()),
                ('teo_cost', models.BigIntegerField(
                    help_text='TEO cost in wei (18 decimals)')),
                ('teacher_bonus', models.BigIntegerField(
                    help_text='Teacher bonus in wei (18 decimals)')),
                ('teacher_commission_rate', models.DecimalField(decimal_places=2,
                 help_text='Commission rate at time of request', max_digits=5)),
                ('teacher_staking_tier', models.CharField(
                    help_text='Staking tier at time of request', max_length=20)),
                ('decision', models.CharField(choices=[('pending', 'Pending Decision'), ('accepted', 'Accepted TeoCoin'), (
                    'declined', 'Declined TeoCoin'), ('expired', 'Decision Expired')], default='pending', max_length=10)),
                ('decision_made_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(
                    help_text='When the decision expires')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student_transaction_hash', models.CharField(
                    blank=True, max_length=66, null=True)),
                ('teacher_payment_completed', models.BooleanField(default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='discount_decisions', to='courses.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='discount_requests', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='discount_decisions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Decisione Sconto Teacher',
                'verbose_name_plural': 'Decisioni Sconti Teacher',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['teacher', 'decision'], name='courses_tea_teacher_894478_idx'), models.Index(fields=['student', 'created_at'], name='courses_tea_student_024751_idx'), models.Index(fields=['expires_at'], name='courses_tea_expires_275f7f_idx')],
            },
        ),
    ]
