# Generated by Django 4.2.11 on 2025-06-16 03:32

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=18)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='token_balance', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Balance Token',
                'verbose_name_plural': 'Balance Token',
            },
        ),
        migrations.CreateModel(
            name='BlockchainTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('mint', 'Mint - Crea nuovi token'), ('transfer', 'Transfer - Trasferimento tra wallet'), ('burn', 'Burn - Distruzione token'), ('course_purchase', 'Course Purchase - Acquisto corso'), ('course_earned', 'Course Earned - Guadagno insegnante'), ('reward', 'Reward - Premio per attività'), ('exercise_reward', 'Exercise Reward - Premio per esercizio completato'), ('review_reward', 'Review Reward - Premio per review completata')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=18)),
                ('from_address', models.CharField(blank=True, max_length=42, null=True)),
                ('to_address', models.CharField(blank=True, max_length=42, null=True)),
                ('tx_hash', models.CharField(blank=True, max_length=66, null=True, unique=True)),
                ('transaction_hash', models.CharField(blank=True, max_length=100, null=True)),
                ('block_number', models.PositiveIntegerField(blank=True, null=True)),
                ('gas_used', models.PositiveIntegerField(blank=True, null=True)),
                ('related_object_id', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'In Attesa'), ('confirmed', 'Confermata'), ('completed', 'Completata'), ('failed', 'Fallita')], default='pending', max_length=10)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blockchain_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transazione Blockchain',
                'verbose_name_plural': 'Transazioni Blockchain',
                'ordering': ['-created_at'],
            },
        ),
    ]
