# Generated by Django 5.2.5 on 2025-08-28 06:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0006_teacherchoicepreference_teacherdiscountdecision"),
        (
            "rewards",
            "0007_remove_paymentdiscountsnapshot_unique_order_id_snapshot_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentdiscountsnapshot",
            name="external_txn_id",
            field=models.CharField(
                blank=True, db_index=True, max_length=120, null=True
            ),
        ),
        migrations.AddField(
            model_name="paymentdiscountsnapshot",
            name="source",
            field=models.CharField(default="local", max_length=16),
        ),
        migrations.AlterField(
            model_name="paymentdiscountsnapshot",
            name="order_id",
            field=models.CharField(
                blank=True, db_index=True, max_length=120, null=True
            ),
        ),
        migrations.AddConstraint(
            model_name="paymentdiscountsnapshot",
            constraint=models.UniqueConstraint(
                condition=models.Q(("external_txn_id", None), _negated=True),
                fields=("external_txn_id",),
                name="uniq_snapshot_by_external_txn",
            ),
        ),
        migrations.AddConstraint(
            model_name="paymentdiscountsnapshot",
            constraint=models.UniqueConstraint(
                condition=models.Q(("order_id", None), _negated=True),
                fields=("order_id",),
                name="uniq_snapshot_by_order_id",
            ),
        ),
    ]
