# Generated by Django 5.2.5 on 2025-08-28 13:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rewards", "0009_paymentdiscountsnapshot_closed_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="blockchaintransaction",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("mint", "Mint - Crea nuovi token"),
                    ("transfer", "Transfer - Trasferimento tra wallet"),
                    ("burn", "Burn - Distruzione token"),
                    ("course_purchase", "Course Purchase - Acquisto corso"),
                    ("course_earned", "Course Earned - Guadagno insegnante"),
                    ("reward", "Reward - Premio per attività"),
                    (
                        "exercise_reward",
                        "Exercise Reward - Premio per esercizio completato",
                    ),
                    ("review_reward", "Review Reward - Premio per review completata"),
                    ("discount_applied", "Discount Applied - Sconto TeoCoin applicato"),
                    ("discount_accept", "Discount Accept - Teacher accepted TEO"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddConstraint(
            model_name="blockchaintransaction",
            constraint=models.UniqueConstraint(
                condition=models.Q(("related_object_id", None), _negated=True),
                fields=("user", "transaction_type", "related_object_id"),
                name="uniq_blockchain_tx_user_type_related",
            ),
        ),
    ]
