# Generated by Django 5.2.5 on 2025-09-01 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rewards", "0010_alter_blockchaintransaction_transaction_type_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="blockchaintransaction",
            name="uniq_blockchain_tx_user_type_related",
        ),
    ]
