# Generated by Django 5.2.5 on 2025-09-10 12:52

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "rewards",
            "0011_remove_blockchaintransaction_uniq_blockchain_tx_user_type_related",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentdiscountsnapshot",
            name="discount_amount_eur",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0"), max_digits=10
            ),
        ),
    ]
