# Generated by Django 5.2.5 on 2025-09-10 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0013_remove_comment_and_recommendations"),
        ("rewards", "0012_add_discount_amount_eur"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentdiscountsnapshot",
            name="decision",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payment_snapshot",
                to="courses.teacherdiscountdecision",
            ),
        ),
    ]
