# Generated by Django 5.2.5 on 2025-09-10 13:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0013_remove_comment_and_recommendations"),
        ("rewards", "0013_add_decision_link"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentdiscountsnapshot",
            name="idempotency_key",
            field=models.CharField(
                blank=True, db_index=True, max_length=200, null=True
            ),
        ),
        migrations.AddConstraint(
            model_name="paymentdiscountsnapshot",
            constraint=models.UniqueConstraint(
                condition=models.Q(("idempotency_key", None), _negated=True),
                fields=("idempotency_key",),
                name="uniq_snapshot_by_idempotency_key",
            ),
        ),
    ]
