# Generated by Django 5.2.5 on 2025-09-10 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rewards", "0002_add_idempotency_fields"),
        ("rewards", "0014_add_idempotency_key"),
        ("rewards", "0014_update_idempotency_unique"),
    ]

    operations = []
