# Generated by Django 5.2.5 on 2025-09-10 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rewards", "0015_merge_20250910_0925"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="paymentdiscountsnapshot",
            name="uniq_snapshot_by_idempotency_key",
        ),
    ]
