# Generated by Django 5.2.5 on 2025-09-10 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "rewards",
            "0016_remove_paymentdiscountsnapshot_uniq_snapshot_by_idempotency_key",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentdiscountsnapshot",
            name="stripe_checkout_session_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Stripe Checkout Session ID for webhook correlation",
                max_length=200,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="paymentdiscountsnapshot",
            name="stripe_payment_intent_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Stripe Payment Intent ID for webhook correlation",
                max_length=200,
                null=True,
            ),
        ),
    ]
