# Salva questo script come clean_unimported.sh e rendilo eseguibile con chmod +x clean_unimported.sh
# Esegui SOLO se sei sicuro di voler eliminare questi file!

rm -v \
src/__mocks__/handlers.js \
src/__mocks__/mockData.js \
src/__mocks__/server.js \
src/components/activity/DattaActivityFeed.jsx \
src/components/activity/RealTimeActivityFeed.jsx \
src/components/admin/AdminAbsorptionOverview.jsx \
src/components/analytics/AnalyticsDashboard.jsx \
src/components/blockchain/BlockchainTransactions.jsx \
src/components/blockchain/DBDiscountInterface.jsx \
src/components/blockchain/DBStakingInterface.jsx \
src/components/blockchain/DBTeoCoinBalance.jsx \
src/components/blockchain/EnhancedDBStakingInterface.jsx \
src/components/blockchain/EnhancedStudentTeoCoinDashboard.jsx \
src/components/blockchain/GasFreeDiscountInterface.jsx \
src/components/blockchain/ManualTeoCoinTransfer.jsx \
src/components/blockchain/MaticUsageChart.jsx \
src/components/blockchain/RewardNotification.jsx \
src/components/blockchain/RewardPoolRefill.jsx \
src/components/blockchain/RewardPoolSummary.jsx \
src/components/blockchain/WalletManager.jsx \
src/components/cards/CourseCard.jsx \
src/components/courses/CourseCheckoutModalNew.jsx \
src/components/courses/CoursePreview.jsx \
src/components/courses/CoursesTableNew.jsx \
src/components/discount/DBTeacherDiscountDashboard.jsx \
src/components/discount/index.js \
src/components/discount/StudentDiscountInterface.jsx \
src/components/discount/TeacherDiscountAbsorptionDashboard.jsx \
src/components/discount/TeacherDiscountDashboard.jsx \
src/components/error/APIErrorBoundary.jsx \
src/components/escrow/index.js \
src/components/escrow/TeacherEscrowCard.jsx \
src/components/escrow/TeacherEscrowManager.jsx \
src/components/escrow/TeacherEscrowNotification.jsx \
src/components/modals/PaymentModal.jsx \
src/components/notifications/NotificationList.jsx \
src/components/teacher/TeacherAbsorptionNotifications.jsx \
src/components/teacher/TeacherDiscountChoiceModal.jsx \
src/components/TeoCoinBalanceDemo/index.js \
src/components/TeoCoinBalanceDemo/TeoCoinBalanceDemo.jsx \
src/components/ui/badge.jsx \
src/components/ui/button.jsx \
src/components/ui/card.jsx \
src/components/ui/index.js \
src/components/ui/input.jsx \
src/components/ui/LazyImage.jsx \
src/components/ui/PaginationOptimized.jsx \
src/components/ui/ProgressIndicator.jsx \
src/components/ui/ReviewerBellNotification.jsx \
src/components/ui/ReviewerNotification.jsx \
src/components/wallet/DattaTeoCoinWallet.jsx \
src/components/wallet/EnhancedTeoCoinWallet.jsx \
src/components/withdrawal/PlatformWithdrawal.jsx \
src/config/development.js \
src/hooks/useBatchApi.js \
src/hooks/useCache.js \
src/hooks/useDebounce.js \
src/hooks/usePagination.js \
src/hooks/usePerformance.js \
src/hooks/useScriptRef.jsx \
src/PrivateRoute.jsx \
src/services/api/adminDashboard.js \
src/services/api/batchApi.js \
src/services/api/blockchain.js \
src/services/api/chat.js \
src/services/api/coursesAdmin.js \
src/services/api/escrow.js \
src/services/api/gasFreeV2.js \
src/services/api/hybrid.js \
src/services/api/index.js \
src/services/api/optimizedApi.js \
src/services/api/teocoin.js \
src/services/api/teocoinDiscount.js \
src/services/api/web3Service_clean.js \
src/services/core/apiClient.js \
src/services/mock/activityAPI.js \
src/services/mock/MockWebSocketService.js \
src/services/mock/teacherAPI.js \
src/services/utils/apiHelpers.js \
src/services/web3ProviderService.js \
src/services/websocket/WebSocketService.js \
src/store/accountReducer.js \
src/utils/devSuppressions.js \
src/utils/performanceTest.js \
src/views/admin/AdminDashboardModern.jsx \
src/views/admin/PendingTeachersTable.jsx \
src/views/admin/RewardPoolDashboard.jsx \
src/views/auth/signin/SignIn1_new.jsx \
src/views/auth/signup/SignUp1_fixed.jsx \
src/views/auth/signup/SignUp1.jsx \
src/views/courses/AllCoursesOptimized.jsx \
src/views/courses/ExerciseGradedDetailNew.jsx \
src/views/courses/StudentCourseDetail.jsx \
src/views/courses/StudentExerciseDetail.jsx \
src/views/courses/StudentLessonDetail.jsx \
src/views/dashboard/AdminDashboard.jsx \
src/views/dashboard/index.jsx \
src/views/dashboard/StudentDashboardModern.jsx \
src/views/dashboard/StudentDashboardOptimized.jsx \
src/views/errors/Unauthorized.jsx \
src/views/landing/LandingPage.jsx \
src/views/profile/index.js \
src/views/profile/NotificationList.jsx \
src/views/profile/NotificationListEnhanced.jsx \
src/views/profile/UserProfile.jsx \
src/views/TeoCoinDemo.jsx \
src/views/TeoCoinIntegrationDemo.jsx