# Generated by Django 4.2.11 on 2025-07-08 09:13

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_created_courses_user_enrolled_courses_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commission_rate', models.DecimalField(decimal_places=2, default=Decimal('50.00'), help_text='Platform commission rate in percentage (e.g., 50.00 = 50%)', max_digits=5)),
                ('staking_tier', models.CharField(choices=[('Bronze', 'Bronze (0 TEO)'), ('Silver', 'Silver (100 TEO)'), ('Gold', 'Gold (300 TEO)'), ('Platinum', 'Platinum (600 TEO)'), ('Diamond', 'Diamond (1,000 TEO)')], default='Bronze', help_text='Current staking tier based on TeoCoin staked', max_length=20)),
                ('staked_teo_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount of TeoCoin currently staked', max_digits=12)),
                ('last_staking_update', models.DateTimeField(auto_now=True, help_text='Last time staking data was synced from blockchain')),
                ('total_earnings_eur', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total EUR earnings from course sales', max_digits=12)),
                ('total_earnings_teo', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total TeoCoin earnings from discount choices', max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(help_text='One-to-one relationship with User model for teachers only', on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Teacher Profile',
                'verbose_name_plural': 'Teacher Profiles',
            },
        ),
    ]
