# Generated by Django 5.2.5 on 2025-08-28 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_teacherprofile_total_courses_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="wallet_nonce",
            field=models.CharField(
                blank=True,
                help_text="Nonce used for wallet linking via signed message",
                max_length=64,
                null=True,
            ),
        ),
    ]
