# Generated by Django 5.2.5 on 2025-08-28 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_user_wallet_nonce"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="wallet_nonce",
            field=models.CharField(
                blank=True,
                help_text="Nonce used for wallet linking SIWE-lite challenge",
                max_length=128,
                null=True,
            ),
        ),
    ]
