# Generated by Django 5.2.5 on 2025-09-10 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0003_notification_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="extra_data",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
